"""
Mock API server (Track B): every endpoint in shared.contracts, with no models, no Docker and no
disk writes, so the UI can be built and demoed without the real backend.

    uvicorn mock.mock_server:app --host 127.0.0.1 --port 8001
    pytest tests/contract --base-url http://127.0.0.1:8001

Tasks replay a scripted run, one event every `release_every_s` seconds (shared/fixtures/
inspection_note.json sets it): the inspection_note fixture for that scenario, built-in scripts
for code_calc, pid_tags and free agent requests. Artifacts are generated in memory (Word via
python-docx, Excel via openpyxl, Python as text). Responses carry X-Contract-Version and
errors use the ApiError shape, exactly like the real backend. Binds to 127.0.0.1 only.
"""
from __future__ import annotations

import copy
import io
import json
import secrets
import threading
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from fastapi import FastAPI, File, HTTPException, Query, Request, UploadFile
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse, Response
from starlette.exceptions import HTTPException as StarletteHTTPException

from shared.contracts import (
    API_PREFIX,
    CONTRACT_VERSION,
    ERROR_CODES,
    AgentEvent,
    ApiError,
    Artifact,
    ArtifactKind,
    AuditRecord,
    ErrorInfo,
    EventsPage,
    EventType,
    FileRef,
    HealthResponse,
    KBHit,
    KBSearchRequest,
    KBSearchResponse,
    KBStats,
    ModelInfo,
    NetworkStatus,
    PlanStep,
    PrewarmResult,
    ProbeRequest,
    ProbeResult,
    RouteDecision,
    RouteRequest,
    Scenario,
    TaskCreate,
    TaskCreated,
    TaskMode,
    TaskState,
    TaskStatus,
    TaskType,
)
from ui.config import ALLOWED_UPLOAD_TYPES

_REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE = _REPO_ROOT / "shared" / "fixtures" / "inspection_note.json"
DEFAULT_RELEASE_S = 1.5
IMAGE_SUFFIXES = {"png", "jpg", "jpeg"}
MEDIA_TYPES = {
    ArtifactKind.DOCX: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ArtifactKind.XLSX: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ArtifactKind.PY: "text/x-python",
}
MODELS = [
    ModelInfo(id="general", ollama_name="qwen3.5:4b", tasks=[TaskType.DOCUMENT, TaskType.GENERAL, TaskType.VISION],
              supports_tools=True, supports_vision=True, loaded=True),
    ModelInfo(id="coder", ollama_name="qwen2.5-coder:3b", tasks=[TaskType.CODING]),
    ModelInfo(id="embed", ollama_name="bge-m3"),
]
KB_HITS = [
    KBHit(text="Minimum PPE for hot work: welding helmet, gloves, fire-resistant clothing.",
          source="nsw_hot_work_petroleum.pdf", page=21, score=0.71),
    KBHit(text="100 ppm of hydrogen sulfide is Immediately Dangerous to Life and Health (IDLH).",
          source="osha_h2s_fact_sheet.pdf", page=1, score=0.66),
]
SOLUTION_PY = ('def pipe_wall_thickness(P: float, D: float, S: float) -> float:\n'
               '    """t = P*D / (2*S), mm."""\n'
               '    return P * D / (2 * S)\n\n\n'
               'if __name__ == "__main__":\n'
               '    print("t = 10 * 200 / (2 * 138) =", round(pipe_wall_thickness(10, 200, 138), 3), "mm")\n')


def now() -> datetime:
    return datetime.now(timezone.utc)


def new_id(prefix: str) -> str:
    return f"{prefix}_{secrets.token_hex(6)}"


def load_fixture() -> dict[str, Any]:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


# ---------------------------------------------------------------- generated deliverables
def docx_bytes(title: str, lines: list[str]) -> bytes:
    from docx import Document

    doc = Document()
    doc.add_heading(title, level=0)
    for line in lines:
        doc.add_paragraph(line)
    doc.add_paragraph("MOCK - generated by mock/mock_server.py, no model was used.")
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def xlsx_bytes(header: list[str], rows: list[list[Any]]) -> bytes:
    from openpyxl import Workbook

    wb = Workbook()
    ws = wb.active
    ws.append(header)
    for row in rows:
        ws.append(row)
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


# ---------------------------------------------------------------- scripted runs
@dataclass
class Script:
    route: RouteDecision
    plan: list[PlanStep]
    events: list[dict[str, Any]]          # {"type", "title", "data", "step"}; "$artifact:N" placeholders
    files: list[tuple[str, ArtifactKind, bytes, str]]   # filename, kind, content, preview
    answer: str


def _route(task_type: TaskType, reason: str, layer: str = "rule") -> RouteDecision:
    model = next(m for m in MODELS if task_type in m.tasks)
    return RouteDecision(task_type=task_type, model_id=model.id, ollama_name=model.ollama_name, reason=reason,
                         layer=layer, confidence=1.0 if layer != "default" else 0.4)


def _tool_events(step: int, tool: str, args: dict, summary: str, model: Optional[str] = None,
                 artifacts: tuple[int, ...] = ()) -> list[dict[str, Any]]:
    out = [{"type": "step_start", "step": step, "title": f"Step {step}: {tool}", "data": {"index": step, "title": tool}},
           {"type": "tool_call", "step": step, "title": tool, "data": {"tool": tool, "args": args}}]
    if model:
        out.append({"type": "llm_call", "step": step, "title": f"{model}: {tool}",
                    "data": {"model_id": model, "purpose": tool, "duration_ms": 1200, "tokens_out": 180}})
    out += [{"type": "artifact", "step": step, "title": "file", "data": {"artifact": f"$artifact:{i}"}} for i in artifacts]
    out.append({"type": "tool_result", "step": step, "title": f"{tool}: ok",
                "data": {"tool": tool, "ok": True, "summary": summary, "duration_ms": 900}})
    return out


def _finish(step: int, answer: str) -> list[dict[str, Any]]:
    return _tool_events(step, "finish", {"answer": answer}, "Finished.") + [
        {"type": "final", "step": None, "title": "Done", "data": {"answer": answer}}]


def _head(route: RouteDecision, plan: list[PlanStep]) -> list[dict[str, Any]]:
    return [{"type": "route", "step": None, "title": f"Routed to {route.task_type.value} ({route.ollama_name})",
             "data": {"decision": route.model_dump(mode="json")}},
            {"type": "plan", "step": None, "title": f"Plan with {len(plan)} steps",
             "data": {"steps": [p.model_dump(mode="json") for p in plan]}}]


def inspection_script() -> Script:
    fx = load_fixture()
    route, plan = RouteDecision.model_validate(fx["route"]), [PlanStep.model_validate(p) for p in fx["plan"]]
    events = []
    for raw in fx["events"]:
        event = copy.deepcopy(raw)
        data = event["data"]
        if data.get("decision") == "$route":
            data["decision"] = route.model_dump(mode="json")
        if data.get("steps") == "$plan":
            data["steps"] = [p.model_dump(mode="json") for p in plan]
        if data.get("artifact") == "$artifact":
            data["artifact"] = "$artifact:0"
        events.append(event)
    art = fx["artifact"]
    word = docx_bytes("INSPECTION APPROVAL NOTE (mock)", [art["preview"], fx["final_answer"]])
    return Script(route, plan, events, [(art["filename"], ArtifactKind.DOCX, word, art["preview"])], fx["final_answer"])


def code_script() -> Script:
    route = _route(TaskType.CODING, "Rule: Coding keywords -> code specialist model (matched 'function')")
    plan = [PlanStep(index=1, title="Write, test and run the calculation code", tool="run_code_task"),
            PlanStep(index=2, title="Report the calculation steps", tool="finish")]
    tests = "from solution import pipe_wall_thickness\n\n\ndef test_known():\n    assert round(pipe_wall_thickness(10, 200, 138), 3) == 7.246\n"
    answer = "t = 10 * 200 / (2 * 138) = 7.246 mm. Code and tests passed in the sandbox (mock)."
    events = _head(route, plan) + _tool_events(1, "run_code_task", {"request": "pipe wall thickness"},
                                               "Code passed its tests: 1 passed, 0 failed, 1 attempt(s).",
                                               model="coder", artifacts=(0, 1)) + _finish(2, answer)
    files = [("solution_mock.py", ArtifactKind.PY, SOLUTION_PY.encode(), SOLUTION_PY),
             ("test_solution_mock.py", ArtifactKind.PY, tests.encode(), tests)]
    return Script(route, plan, events, files, answer)


def pid_script() -> Script:
    route = _route(TaskType.VISION, "Rule: Image attached -> vision-capable model")
    plan = [PlanStep(index=1, title="Read the P&ID drawing in tiles", tool="read_document"),
            PlanStep(index=2, title="Extract the tag list to Excel", tool="extract_pid_tags"),
            PlanStep(index=3, title="Summarise the tag counts", tool="finish")]
    rows = [["P-201A", "Pump"], ["P-201B", "Pump"], ["FT-201", "Flow transmitter"], ["V-201", "Vessel"]]
    answer = "4 unique tags: 2 Pump, 1 Flow transmitter, 1 Vessel (mock)."
    events = (_head(route, plan)
              + _tool_events(1, "read_document", {"file_id": "f_mock", "kind": "pid"}, "doc_1: 4 tiles read")
              + _tool_events(2, "extract_pid_tags", {"doc_id": "doc_1"}, answer, artifacts=(0,)) + _finish(3, answer))
    return Script(route, plan, events, [("pid_tags_mock.xlsx", ArtifactKind.XLSX,
                                         xlsx_bytes(["Tag", "Equipment type"], rows), answer)], answer)


def agent_script(message: str) -> Script:
    route = _route(TaskType.GENERAL, "Default: no rule matched (mock)", layer="default")
    plan = [PlanStep(index=1, title="Answer from the SOPs", tool="answer_question"),
            PlanStep(index=2, title="Report", tool="finish")]
    answer = (f"Mock answer to: {message[:120]}\n\n100 ppm of H2S is IDLH [1].\n\n"
              "Sources:\n[1] osha_h2s_fact_sheet.pdf, p.1")
    events = (_head(route, plan) + _tool_events(1, "answer_question", {"question": message}, answer, model="general")
              + _finish(2, answer))
    return Script(route, plan, events, [], answer)


def script_for(request: TaskCreate) -> Script:
    if request.scenario == Scenario.INSPECTION_NOTE:
        return inspection_script()
    if request.scenario == Scenario.CODE_CALC:
        return code_script()
    if request.scenario == Scenario.PID_TAGS:
        return pid_script()
    return agent_script(request.message)


# ---------------------------------------------------------------- in-memory state
@dataclass
class MockTask:
    request: TaskCreate
    task_id: str
    created_at: datetime
    started: float
    script: Script
    release_s: float
    artifacts: list[Artifact] = field(default_factory=list)
    cancelled_after: Optional[int] = None     # events released when the cancel arrived

    def events(self) -> list[AgentEvent]:
        total = len(self.script.events)
        released = min(total, int((time.monotonic() - self.started) / self.release_s) + 1)
        if self.cancelled_after is not None:
            released = min(released, self.cancelled_after)
        out = [self._event(i + 1, raw) for i, raw in enumerate(self.script.events[:released])]
        if self.cancelled_after is not None:
            error = ErrorInfo(code="CANCELLED", message=ERROR_CODES["CANCELLED"]).model_dump()
            out.append(AgentEvent(seq=len(out) + 1, task_id=self.task_id, ts=now(), type=EventType.ERROR,
                                  title="Cancelled", data={"error": error}))
        return out

    def _event(self, seq: int, raw: dict[str, Any]) -> AgentEvent:
        data = copy.deepcopy(raw["data"])
        ref = data.get("artifact")
        if isinstance(ref, str) and ref.startswith("$artifact:"):
            art = self.artifacts[int(ref.split(":")[1])]
            data["artifact"] = art.model_dump(mode="json")
            raw = {**raw, "title": art.filename}
        return AgentEvent(seq=seq, task_id=self.task_id, ts=self.created_at, type=EventType(raw["type"]),
                          step=raw.get("step"), title=raw["title"], data=data)

    def status(self) -> TaskStatus:
        if self.cancelled_after is not None:
            return TaskStatus.CANCELLED
        events = self.events()
        return TaskStatus.SUCCEEDED if len(events) == len(self.script.events) else TaskStatus.RUNNING

    def state(self) -> TaskState:
        status, events = self.status(), self.events()
        released = [e.data["artifact"]["artifact_id"] for e in events if e.type == EventType.ARTIFACT]
        done = status != TaskStatus.RUNNING
        return TaskState(
            task_id=self.task_id, status=status, mode=self.request.mode, scenario=self.request.scenario,
            message=self.request.message, file_ids=self.request.file_ids, route=self.script.route,
            plan=self.script.plan, final_answer=self.script.answer if status == TaskStatus.SUCCEEDED else None,
            artifacts=[a for a in self.artifacts if a.artifact_id in released],
            error=ErrorInfo(code="CANCELLED", message=ERROR_CODES["CANCELLED"]) if status == TaskStatus.CANCELLED else None,
            created_at=self.created_at, started_at=self.created_at, finished_at=now() if done else None,
            elapsed_s=round(time.monotonic() - self.started, 1))


class MockState:
    def __init__(self) -> None:
        self.lock = threading.Lock()
        self.tasks: dict[str, MockTask] = {}
        self.files: dict[str, FileRef] = {}
        self.artifacts: dict[str, tuple[Artifact, bytes]] = {}
        self.audit: list[AuditRecord] = []
        self.release_s = float(load_fixture().get("release_every_s", DEFAULT_RELEASE_S))

    def record(self, kind: str, name: str, task_id: Optional[str] = None, **detail: Any) -> None:
        self.audit.append(AuditRecord(ts=now(), task_id=task_id, kind=kind, name=name, detail=detail))

    def create_task(self, request: TaskCreate) -> MockTask:
        task = MockTask(request=request, task_id=new_id("t"), created_at=now(), started=time.monotonic(),
                        script=script_for(request), release_s=self.release_s)
        for filename, kind, content, preview in task.script.files:
            art = Artifact(artifact_id=new_id("a"), task_id=task.task_id, filename=filename, kind=kind,
                           size_bytes=len(content), created_at=task.created_at, download_url="",
                           preview=preview[:500])
            art.download_url = f"{API_PREFIX}/artifacts/{art.artifact_id}"
            task.artifacts.append(art)
            self.artifacts[art.artifact_id] = (art, content)
        self.tasks[task.task_id] = task
        self.record("system", "task_created", task.task_id, mode=request.mode.value, files=len(request.file_ids))
        self.record("llm", "general", task.task_id, purpose="plan (mock)")
        return task


state = MockState()
app = FastAPI(title="Sovereign AI Workbench MOCK API", docs_url=None, redoc_url=None)


# ---------------------------------------------------------------- errors + header (same shape as the backend)
def error_response(status: int, code: str, message: Optional[str] = None) -> JSONResponse:
    body = ApiError(error=ErrorInfo(code=code, message=message or ERROR_CODES.get(code, code)))
    return JSONResponse(status_code=status, content=body.model_dump(mode="json"),
                        headers={"X-Contract-Version": CONTRACT_VERSION})


def fail(status: int, code: str, message: Optional[str] = None) -> HTTPException:
    return HTTPException(status_code=status, detail={"code": code, "message": message or ERROR_CODES[code]})


@app.middleware("http")
async def _contract_header(request: Request, call_next):
    response = await call_next(request)
    response.headers["X-Contract-Version"] = CONTRACT_VERSION
    return response


@app.exception_handler(RequestValidationError)
async def _validation(request: Request, exc: RequestValidationError) -> JSONResponse:
    return error_response(422, "BAD_REQUEST", f"Request body failed validation: {exc.errors()}")


@app.exception_handler(StarletteHTTPException)
async def _http(request: Request, exc: StarletteHTTPException) -> JSONResponse:
    if isinstance(exc.detail, dict):
        return error_response(exc.status_code, exc.detail["code"], exc.detail.get("message"))
    return error_response(exc.status_code, "INTERNAL" if exc.status_code >= 500 else "BAD_REQUEST", str(exc.detail))


def get_task_or_404(task_id: str) -> MockTask:
    task = state.tasks.get(task_id)
    if task is None:
        raise fail(404, "TASK_NOT_FOUND")
    return task


# ---------------------------------------------------------------- endpoints
@app.get(f"{API_PREFIX}/health", response_model=HealthResponse)
def health() -> HealthResponse:
    return HealthResponse(status="ok", contract_version=CONTRACT_VERSION, mock=True, ollama_ok=True, sandbox_ok=True,
                          tesseract_ok=True, kb_chunks=185, models=MODELS, time=now())


@app.get(f"{API_PREFIX}/models", response_model=list[ModelInfo])
def models() -> list[ModelInfo]:
    return MODELS


@app.post(f"{API_PREFIX}/admin/prewarm", response_model=PrewarmResult)
def prewarm() -> PrewarmResult:
    state.record("system", "prewarm")
    return PrewarmResult(warmed=[m.id for m in MODELS], duration_ms=5)


@app.post(f"{API_PREFIX}/files", response_model=FileRef)
async def upload(file: UploadFile = File(...)) -> FileRef:
    name = file.filename or "upload"
    suffix = name.rsplit(".", 1)[-1].lower() if "." in name else ""
    if suffix not in ALLOWED_UPLOAD_TYPES:
        raise fail(415, "UNSUPPORTED_FILE")
    content = await file.read()
    ref = FileRef(file_id=new_id("f"), filename=name, mime_type=file.content_type or "application/octet-stream",
                  size_bytes=len(content), is_image=suffix in IMAGE_SUFFIXES,
                  pages=1 if suffix == "pdf" else None, has_text_layer=False if suffix == "pdf" else None)
    state.files[ref.file_id] = ref
    return ref


@app.post(f"{API_PREFIX}/route", response_model=RouteDecision)
def route(request: RouteRequest) -> RouteDecision:
    if any(state.files.get(f) is not None and state.files[f].is_image for f in request.file_ids):
        return _route(TaskType.VISION, "Rule: Image attached -> vision-capable model")
    text = request.message.lower()
    if any(word in text for word in ("code", "python", "function", "script")):
        return _route(TaskType.CODING, "Rule: Coding keywords -> code specialist model")
    if any(word in text for word in ("report", "sop", "summar", "approval note", "presentation")):
        return _route(TaskType.DOCUMENT, "Rule: Document keywords -> document agent")
    return _route(TaskType.GENERAL, "Default: no rule matched (mock)", layer="default")


@app.post(f"{API_PREFIX}/tasks", response_model=TaskCreated, status_code=202)
def create_task(request: TaskCreate) -> TaskCreated:
    if request.mode == TaskMode.GUIDED and request.scenario is None:
        raise fail(422, "BAD_REQUEST", "Guided mode needs a scenario.")
    with state.lock:
        task = state.create_task(request)
    return TaskCreated(task_id=task.task_id, status=TaskStatus.QUEUED)


@app.get(f"{API_PREFIX}/tasks/{{task_id}}", response_model=TaskState)
def get_task(task_id: str) -> TaskState:
    return get_task_or_404(task_id).state()


@app.get(f"{API_PREFIX}/tasks/{{task_id}}/events", response_model=EventsPage)
def get_events(task_id: str, after: int = Query(default=0, ge=0)) -> EventsPage:
    task = get_task_or_404(task_id)
    events = task.events()
    page = [e for e in events if e.seq > after]
    done = task.status() != TaskStatus.RUNNING
    if done and not any(r.task_id == task_id and r.name == "task_finished" for r in state.audit):
        state.record("system", "task_finished", task_id, status=task.status().value)
    return EventsPage(task_id=task_id, events=page, next_seq=page[-1].seq if page else after, done=done)


@app.post(f"{API_PREFIX}/tasks/{{task_id}}/cancel", response_model=TaskState)
def cancel(task_id: str) -> TaskState:
    task = get_task_or_404(task_id)
    with state.lock:
        if task.status() == TaskStatus.RUNNING:
            task.cancelled_after = len(task.events())
            state.record("system", "task_cancelled", task_id)
    return task.state()


@app.get(f"{API_PREFIX}/artifacts/{{artifact_id}}")
def artifact(artifact_id: str) -> Response:
    if ".." in artifact_id or "/" in artifact_id or "\\" in artifact_id:
        raise fail(400, "BAD_REQUEST", "artifact_id must not contain path characters")
    found = state.artifacts.get(artifact_id)
    if found is None:
        raise fail(404, "FILE_NOT_FOUND", f"no artifact with id {artifact_id!r}")
    art, content = found
    return Response(content, media_type=MEDIA_TYPES.get(art.kind, "application/octet-stream"),
                    headers={"Content-Disposition": f'attachment; filename="{art.filename}"'})


@app.get(f"{API_PREFIX}/network/status", response_model=NetworkStatus)
def network_status() -> NetworkStatus:
    return NetworkStatus(checked_at=now(), external_count=0, external_seen_since_start=0, total_connections=0,
                         firewall_outbound_blocked=None, connections=[], since=now(), attempts_since_start=0,
                         other_apps_since_start=0, probe_since_start=0, platform_seen_since_start=0,
                         platform_attempts_since_start=0)


@app.post(f"{API_PREFIX}/network/probe", response_model=ProbeResult)
def network_probe(request: ProbeRequest) -> ProbeResult:
    # The mock never opens a connection: it reports what the sealed demo laptop reports.
    state.record("network", "probe", target=request.target)
    return ProbeResult(target=request.target, reachable=False, error="mock: no connection attempted", duration_ms=0)


@app.get(f"{API_PREFIX}/kb/stats", response_model=KBStats)
def kb_stats() -> KBStats:
    return KBStats(documents=5, chunks=185, embed_model="bge-m3")


@app.post(f"{API_PREFIX}/kb/search", response_model=KBSearchResponse)
def kb_search(request: KBSearchRequest) -> KBSearchResponse:
    return KBSearchResponse(hits=KB_HITS[:request.top_k])


@app.get(f"{API_PREFIX}/audit", response_model=list[AuditRecord])
def audit(task_id: Optional[str] = None, limit: int = Query(default=100, ge=1, le=1000)) -> list[AuditRecord]:
    records = [r for r in reversed(state.audit) if task_id is None or r.task_id == task_id]
    return records[:limit]
